CLASS LHC_GEN_RAP1_DTL DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEDTLID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  gen_rap1_dtl~CalculateDtlID .
ENDCLASS.

CLASS LHC_GEN_RAP1_DTL IMPLEMENTATION.
  METHOD CALCULATEDTLID.
  ENDMETHOD.
ENDCLASS.
