    CLASS zcl_data_penalty_price DEFINITION
      PUBLIC
      FINAL
      CREATE PUBLIC .

      PUBLIC SECTION.

      PROTECTED SECTION.
      PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_DATA_PENALTY_PRICE IMPLEMENTATION.
ENDCLASS.
