CLASS LHC_ZCR_OD_21 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      UPDATE FOR MODIFY
        IMPORTING
          ENTITIES FOR UPDATE  ZCR_OD_21,
      DELETE FOR MODIFY
        IMPORTING
          KEYS FOR DELETE  ZCR_OD_21,
      READ FOR READ
        IMPORTING
          KEYS FOR READ  ZCR_OD_21
        RESULT result,
      RBA_ZCR_OD_2 FOR READ
        IMPORTING
          KEYS_RBA FOR READ  ZCR_OD_21\_ZCR_OD_2
        FULL result_requested
        RESULT result
        LINK association_links.
ENDCLASS.

CLASS LHC_ZCR_OD_21 IMPLEMENTATION.
  METHOD UPDATE.
  ENDMETHOD.
  METHOD DELETE.
  ENDMETHOD.
  METHOD READ.
  ENDMETHOD.
  METHOD RBA_ZCR_OD_2.
  ENDMETHOD.
ENDCLASS.
