CLASS LHC_ZCR_OD_3 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      UPDATE FOR MODIFY
        IMPORTING
          ENTITIES FOR UPDATE  ZCR_OD_3,
      DELETE FOR MODIFY
        IMPORTING
          KEYS FOR DELETE  ZCR_OD_3,
      READ FOR READ
        IMPORTING
          KEYS FOR READ  ZCR_OD_3
        RESULT result,
      RBA_ZCR_OD_2 FOR READ
        IMPORTING
          KEYS_RBA FOR READ  ZCR_OD_3\_ZCR_OD_2
        FULL result_requested
        RESULT result
        LINK association_links,
      CBA_ZCR_OD_4 FOR MODIFY
        IMPORTING
          ENTITIES_CBA FOR CREATE  ZCR_OD_3\_ZCR_OD_4,
      RBA_ZCR_OD_4 FOR READ
        IMPORTING
          KEYS_RBA FOR READ  ZCR_OD_3\_ZCR_OD_4
        FULL result_requested
        RESULT result
        LINK association_links.
ENDCLASS.

CLASS LHC_ZCR_OD_3 IMPLEMENTATION.
  METHOD UPDATE.
  ENDMETHOD.
  METHOD DELETE.
  ENDMETHOD.
  METHOD READ.
  ENDMETHOD.
  METHOD RBA_ZCR_OD_2.
  ENDMETHOD.
  METHOD CBA_ZCR_OD_4.
  ENDMETHOD.
  METHOD RBA_ZCR_OD_4.
  ENDMETHOD.
ENDCLASS.
