CLASS LHC_ZCR_OD_GC DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZCR_OD_GC
        RESULT result,
      CREATE FOR MODIFY
        IMPORTING
          ENTITIES FOR CREATE  ZCR_OD_GC,
      UPDATE FOR MODIFY
        IMPORTING
          ENTITIES FOR UPDATE  ZCR_OD_GC,
      DELETE FOR MODIFY
        IMPORTING
          KEYS FOR DELETE  ZCR_OD_GC,
      LOCK FOR LOCK
        IMPORTING
          KEYS FOR LOCK  ZCR_OD_GC,
      READ FOR READ
        IMPORTING
          KEYS FOR READ  ZCR_OD_GC
        RESULT result,
      CBA_ZCR_OD_2 FOR MODIFY
        IMPORTING
          ENTITIES_CBA FOR CREATE  ZCR_OD_GC\_ZCR_OD_2,
      RBA_ZCR_OD_2 FOR READ
        IMPORTING
          KEYS_RBA FOR READ  ZCR_OD_GC\_ZCR_OD_2
        FULL result_requested
        RESULT result
        LINK association_links.
ENDCLASS.

CLASS LHC_ZCR_OD_GC IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD CREATE.
  ENDMETHOD.
  METHOD UPDATE.
  ENDMETHOD.
  METHOD DELETE.
  ENDMETHOD.
  METHOD LOCK.
  ENDMETHOD.
  METHOD READ.
  ENDMETHOD.
  METHOD CBA_ZCR_OD_2.
  ENDMETHOD.
  METHOD RBA_ZCR_OD_2.
  ENDMETHOD.
ENDCLASS.
CLASS LCL_ZR_ZCR_OD_GC02TP DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_SAVER.
  PROTECTED SECTION.
    METHODS:
      FINALIZE REDEFINITION,
      CHECK_BEFORE_SAVE REDEFINITION,
      SAVE REDEFINITION,
      CLEANUP REDEFINITION,
      CLEANUP_FINALIZE REDEFINITION.
ENDCLASS.

CLASS LCL_ZR_ZCR_OD_GC02TP IMPLEMENTATION.
  METHOD FINALIZE.
  ENDMETHOD.
  METHOD CHECK_BEFORE_SAVE.
  ENDMETHOD.
  METHOD SAVE.
  ENDMETHOD.
  METHOD CLEANUP.
  ENDMETHOD.
  METHOD CLEANUP_FINALIZE.
  ENDMETHOD.
ENDCLASS.
