CLASS LHC_ZCR_OD_4 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      UPDATE FOR MODIFY
        IMPORTING
          ENTITIES FOR UPDATE  ZCR_OD_4,
      DELETE FOR MODIFY
        IMPORTING
          KEYS FOR DELETE  ZCR_OD_4,
      READ FOR READ
        IMPORTING
          KEYS FOR READ  ZCR_OD_4
        RESULT result,
      RBA_ZCR_OD_3 FOR READ
        IMPORTING
          KEYS_RBA FOR READ  ZCR_OD_4\_ZCR_OD_3
        FULL result_requested
        RESULT result
        LINK association_links.
ENDCLASS.

CLASS LHC_ZCR_OD_4 IMPLEMENTATION.
  METHOD UPDATE.
  ENDMETHOD.
  METHOD DELETE.
  ENDMETHOD.
  METHOD READ.
  ENDMETHOD.
  METHOD RBA_ZCR_OD_3.
  ENDMETHOD.
ENDCLASS.
