CLASS lhc_XMLFormConfig DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PUBLIC SECTION.
*    INTERFACES IF_MBC_CP_RAP_TDAT_CTS.

  PRIVATE SECTION.

    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR XMLFormConfig RESULT RESULT.

    METHODS GET_INSTANCE_FEATURES FOR INSTANCE FEATURES
      IMPORTING KEYS REQUEST REQUESTED_FEATURES FOR XMLFormConfig RESULT RESULT.

    METHODS EDIT FOR MODIFY
      IMPORTING KEYS FOR ACTION XMLFORMCONFIG~EDIT.

ENDCLASS.

CLASS lhc_XMLFormConfig IMPLEMENTATION.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD GET_INSTANCE_FEATURES.
  ENDMETHOD.

  METHOD Edit.

  ENDMETHOD.

ENDCLASS.
