CLASS lhc_ZI_FIRUD_CF_OFF_ODATA DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_FIRUD_CF_OFF_ODATA RESULT RESULT.

ENDCLASS.

CLASS lhc_ZI_FIRUD_CF_OFF_ODATA IMPLEMENTATION.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

ENDCLASS.
