CLASS LHC_ZR_TBREPORT DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZrTbreport
        RESULT result,
         get_instance_features FOR INSTANCE FEATURES
        IMPORTING keys REQUEST requested_features FOR ZrTbreport RESULT result.
ENDCLASS.

CLASS LHC_ZR_TBREPORT IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

     METHOD get_instance_features.
  ENDMETHOD.
ENDCLASS.
