CLASS lhc_pktPDF DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR pktPDF RESULT RESULT.

    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR pktPDF RESULT RESULT.

    METHODS CREATE FOR MODIFY
      IMPORTING ENTITIES FOR CREATE pktPDF.

    METHODS UPDATE FOR MODIFY
      IMPORTING ENTITIES FOR UPDATE pktPDF.

    METHODS DELETE FOR MODIFY
      IMPORTING KEYS FOR DELETE pktPDF.

    METHODS READ FOR READ
      IMPORTING KEYS FOR READ pktPDF RESULT RESULT.

    METHODS LOCK FOR LOCK
      IMPORTING KEYS FOR LOCK pktPDF.

ENDCLASS.

CLASS lhc_pktPDF IMPLEMENTATION.

  METHOD GET_INSTANCE_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD CREATE.
  ENDMETHOD.

  METHOD UPDATE.
  ENDMETHOD.

  METHOD DELETE.
  ENDMETHOD.

  METHOD READ.
    DATA: IR_COMPANYCODE        TYPE ZCL_JP_COMMON_CORE=>TT_RANGES,
          IR_ACCOUNTINGDOCUMENT TYPE ZCL_JP_COMMON_CORE=>TT_RANGES,
          IR_FISCALYEAR         TYPE ZCL_JP_COMMON_CORE=>TT_RANGES,
          IR_ACCOUNTANT         TYPE ZCL_JP_COMMON_CORE=>TT_RANGES,
          IR_CREATEBY           TYPE ZCL_JP_COMMON_CORE=>TT_RANGES.

    LOOP AT KEYS INTO DATA(K).

      ZCL_JP_GET_DATA_REPORT_FI=>GET_PKT_PDF(
        EXPORTING
          IR_COMPANYCODE        = IR_COMPANYCODE
          IR_ACCOUNTINGDOCUMENT = IR_ACCOUNTINGDOCUMENT
          IR_FISCALYEAR         = IR_FISCALYEAR
          IR_ACCOUNTANT         = IR_ACCOUNTANT
          IR_CREATEBY           = IR_CREATEBY
        IMPORTING
          E_PKT_PDT             = DATA(LT_PKT_PDF)
      ).

      READ TABLE LT_PKT_PDF INDEX 1 INTO DATA(LS_PKT_PDF).
      IF SY-SUBRC EQ 0.
        APPEND VALUE #(
              CompanyCode        = K-COMPANYCODE
              AccountingDocument = K-ACCOUNTINGDOCUMENT
              FiscalYear         = K-FiscalYear
              Accountant         = K-ACCOUNTANT
              CREATEBY           = K-CREATEBY
              Content            = LS_PKT_PDF-Content
              MimeType           = LS_PKT_PDF-MimeType
              FileName           = LS_PKT_PDF-FileName
              FileExtension      = LS_PKT_PDF-fileExtension
        ) TO RESULT.
      ENDIF.

    ENDLOOP.
  ENDMETHOD.

  METHOD LOCK.
  ENDMETHOD.

ENDCLASS.

CLASS lsc_ZJP_C_PKT_PDFDOC DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_SAVER.
  PROTECTED SECTION.

    METHODS FINALIZE REDEFINITION.

    METHODS CHECK_BEFORE_SAVE REDEFINITION.

    METHODS SAVE REDEFINITION.

    METHODS CLEANUP REDEFINITION.

    METHODS CLEANUP_FINALIZE REDEFINITION.

ENDCLASS.

CLASS lsc_ZJP_C_PKT_PDFDOC IMPLEMENTATION.

  METHOD FINALIZE.
  ENDMETHOD.

  METHOD CHECK_BEFORE_SAVE.
  ENDMETHOD.

  METHOD SAVE.
  ENDMETHOD.

  METHOD CLEANUP.
  ENDMETHOD.

  METHOD CLEANUP_FINALIZE.
  ENDMETHOD.

ENDCLASS.
